with open('apps/alerts/notifications.py', 'w') as f:
    f.write('from django.core.mail import send_mail\n')
    f.write('from django.conf import settings\n')
    f.write('from apps.accounts.models import User\n\n')
    f.write('def send_counterfeit_alert_email(alert):\n')
    f.write('    regulators = User.objects.filter(role="regulator", is_active=True)\n')
    f.write('    emails = list(regulators.values_list("email", flat=True))\n')
    f.write('    if not emails:\n')
    f.write('        return\n')
    f.write('    subject = f"[URGENT] {alert.severity.upper()} Alert: {alert.title}"\n')
    f.write('    message = f"Alert Type: {alert.alert_type}\\nSeverity: {alert.severity}\\nMessage: {alert.message}\\n"\n')
    f.write('    send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, emails, fail_silently=True)\n\n')
    f.write('def send_recall_alert_email(alert):\n')
    f.write('    pharmacists = User.objects.filter(role="pharmacist", is_active=True)\n')
    f.write('    wholesalers = User.objects.filter(role="wholesaler", is_active=True)\n')
    f.write('    emails = list(pharmacists.values_list("email", flat=True)) + list(wholesalers.values_list("email", flat=True))\n')
    f.write('    if not emails:\n')
    f.write('        return\n')
    f.write('    subject = f"[RECALL NOTICE] {alert.title}"\n')
    f.write('    message = f"A drug recall has been issued.\\nMessage: {alert.message}\\n"\n')
    f.write('    send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, emails, fail_silently=True)\n')
print('Done')
