with open('apps/accounts/models.py', 'w') as f:
    f.write('from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin\n')
    f.write('from django.db import models\n')
    f.write('from django.utils import timezone\n')
    f.write('from django.utils.translation import gettext_lazy as _\n')
    f.write('import uuid\n')
    f.write('from .managers import UserManager\n\n')
    f.write('class User(AbstractBaseUser, PermissionsMixin):\n')
    f.write('    class Roles(models.TextChoices):\n')
    f.write('        MANUFACTURER = "manufacturer", _("Manufacturer")\n')
    f.write('        WHOLESALER = "wholesaler", _("Wholesaler")\n')
    f.write('        PHARMACIST = "pharmacist", _("Pharmacist")\n')
    f.write('        REGULATOR = "regulator", _("Regulator")\n')
    f.write('        PATIENT = "patient", _("Patient")\n\n')
    f.write('    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)\n')
    f.write('    email = models.EmailField(_("email address"), unique=True)\n')
    f.write('    phone = models.CharField(max_length=20, blank=True)\n')
    f.write('    role = models.CharField(max_length=20, choices=Roles.choices, default=Roles.PATIENT)\n')
    f.write('    company_name = models.CharField(max_length=200, blank=True)\n')
    f.write('    license_number = models.CharField(max_length=100, blank=True)\n')
    f.write('    is_staff = models.BooleanField(default=False)\n')
    f.write('    is_active = models.BooleanField(default=True)\n')
    f.write('    is_verified = models.BooleanField(default=False)\n')
    f.write('    date_joined = models.DateTimeField(default=timezone.now)\n')
    f.write('    last_login = models.DateTimeField(null=True, blank=True)\n')
    f.write('    deleted_at = models.DateTimeField(null=True, blank=True)\n\n')
    f.write('    objects = UserManager()\n\n')
    f.write('    USERNAME_FIELD = "email"\n')
    f.write('    REQUIRED_FIELDS = []\n\n')
    f.write('    class Meta:\n')
    f.write('        db_table = "users"\n')
    f.write('        ordering = ["-date_joined"]\n\n')
    f.write('    def __str__(self):\n')
    f.write('        return f"{self.email} ({self.role})"\n\n')
    f.write('    def soft_delete(self):\n')
    f.write('        self.deleted_at = timezone.now()\n')
    f.write('        self.is_active = False\n')
    f.write('        self.save()\n\n')
    f.write('    def restore(self):\n')
    f.write('        self.deleted_at = None\n')
    f.write('        self.is_active = True\n')
    f.write('        self.save()\n\n')
    f.write('class ManufacturerProfile(models.Model):\n')
    f.write('    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="manufacturer_profile")\n')
    f.write('    registration_number = models.CharField(max_length=100, unique=True)\n')
    f.write('    address = models.TextField(blank=True)\n\n')
    f.write('    class Meta:\n')
    f.write('        db_table = "manufacturers"\n\n')
    f.write('    def __str__(self):\n')
    f.write('        return f"Manufacturer: {self.user.company_name}"\n')
print('Done')
