with open('apps/verification/models.py', 'w') as f:
    f.write('from django.db import models\n')
    f.write('from django.utils.translation import gettext_lazy as _\n')
    f.write('import uuid\n\n')
    f.write('class VerificationLog(models.Model):\n')
    f.write('    class Result(models.TextChoices):\n')
    f.write('        AUTHENTIC = "authentic", _("Authentic")\n')
    f.write('        COUNTERFEIT = "counterfeit", _("Counterfeit")\n')
    f.write('        EXPIRED = "expired", _("Expired")\n')
    f.write('        RECALLED = "recalled", _("Recalled")\n')
    f.write('        NOT_FOUND = "not_found", _("Not Found")\n\n')
    f.write('    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)\n')
    f.write('    batch = models.ForeignKey("drugs.BatchNumber", on_delete=models.SET_NULL, null=True, blank=True, related_name="verification_logs")\n')
    f.write('    verified_by = models.ForeignKey("accounts.User", on_delete=models.SET_NULL, null=True, blank=True, related_name="verifications")\n')
    f.write('    scanned_code = models.CharField(max_length=255)\n')
    f.write('    result = models.CharField(max_length=20, choices=Result.choices)\n')
    f.write('    ip_address = models.GenericIPAddressField(null=True, blank=True)\n')
    f.write('    location = models.CharField(max_length=255, blank=True)\n')
    f.write('    verified_at = models.DateTimeField(auto_now_add=True)\n\n')
    f.write('    class Meta:\n')
    f.write('        db_table = "verification_logs"\n')
    f.write('        ordering = ["-verified_at"]\n\n')
    f.write('    def __str__(self):\n')
    f.write('        return f"{self.scanned_code} - {self.result}"\n')
print('Done')
