with open('apps/common/qr_utils.py', 'w') as f:
    f.write('import qrcode\n')
    f.write('import io\n')
    f.write('import base64\n')
    f.write('import json\n')
    f.write('import hashlib\n')
    f.write('import hmac\n')
    f.write('import os\n\n')
    f.write('def generate_batch_qr(batch_number, drug_id, manufacturer_id, secret_key=None):\n')
    f.write('    if secret_key is None:\n')
    f.write('        secret_key = os.environ.get("QR_SECRET_KEY", "dev-secret-key")\n')
    f.write('    payload = {"b": batch_number, "d": str(drug_id), "m": str(manufacturer_id), "v": "1"}\n')
    f.write('    data_string = json.dumps(payload, sort_keys=True, separators=(",", ":"))\n')
    f.write('    signature = hmac.new(secret_key.encode(), data_string.encode(), hashlib.sha256).hexdigest()[:16]\n')
    f.write('    payload["h"] = signature\n')
    f.write('    qr = qrcode.QRCode(version=3, box_size=10, border=4)\n')
    f.write('    qr.add_data(json.dumps(payload))\n')
    f.write('    qr.make(fit=True)\n')
    f.write('    img = qr.make_image(fill_color="black", back_color="white")\n')
    f.write('    buffer = io.BytesIO()\n')
    f.write('    img.save(buffer, format="PNG")\n')
    f.write('    img_str = base64.b64encode(buffer.getvalue()).decode()\n')
    f.write('    return {"qr_data": payload, "qr_image_base64": img_str, "batch_number": batch_number}\n\n')
    f.write('def verify_qr_code(scanned_data, secret_key=None):\n')
    f.write('    try:\n')
    f.write('        data = json.loads(scanned_data)\n')
    f.write('        if "b" not in data or "d" not in data:\n')
    f.write('            return {"valid": False, "error": "Missing required fields"}\n')
    f.write('        if "h" in data:\n')
    f.write('            if secret_key is None:\n')
    f.write('                secret_key = os.environ.get("QR_SECRET_KEY", "dev-secret-key")\n')
    f.write('            verify_payload = {k: v for k, v in data.items() if k != "h"}\n')
    f.write('            data_string = json.dumps(verify_payload, sort_keys=True, separators=(",", ":"))\n')
    f.write('            expected_sig = hmac.new(secret_key.encode(), data_string.encode(), hashlib.sha256).hexdigest()[:16]\n')
    f.write('            if not hmac.compare_digest(data["h"], expected_sig):\n')
    f.write('                return {"valid": False, "error": "Invalid signature"}\n')
    f.write('        return {"valid": True, "batch_number": data.get("b"), "drug_id": data.get("d"), "manufacturer_id": data.get("m")}\n')
    f.write('    except Exception as e:\n')
    f.write('        return {"valid": False, "error": str(e)}\n')
print('Done')
