with open('apps/alerts/models.py', 'w') as f:
    f.write('from django.db import models\n')
    f.write('from django.utils.translation import gettext_lazy as _\n')
    f.write('import uuid\n\n')
    f.write('class Alert(models.Model):\n')
    f.write('    class Severity(models.TextChoices):\n')
    f.write('        LOW = "low", _("Low")\n')
    f.write('        MEDIUM = "medium", _("Medium")\n')
    f.write('        HIGH = "high", _("High")\n')
    f.write('        CRITICAL = "critical", _("Critical")\n\n')
    f.write('    class AlertType(models.TextChoices):\n')
    f.write('        COUNTERFEIT = "counterfeit", _("Counterfeit Detected")\n')
    f.write('        RECALL = "recall", _("Drug Recall")\n')
    f.write('        EXPIRY = "expiry", _("Expiry Warning")\n')
    f.write('        SUSPICIOUS = "suspicious", _("Suspicious Activity")\n\n')
    f.write('    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)\n')
    f.write('    drug = models.ForeignKey("drugs.Drug", on_delete=models.CASCADE, related_name="alerts", null=True, blank=True)\n')
    f.write('    alert_type = models.CharField(max_length=20, choices=AlertType.choices)\n')
    f.write('    severity = models.CharField(max_length=20, choices=Severity.choices, default=Severity.MEDIUM)\n')
    f.write('    title = models.CharField(max_length=255)\n')
    f.write('    message = models.TextField()\n')
    f.write('    is_resolved = models.BooleanField(default=False)\n')
    f.write('    created_by = models.ForeignKey("accounts.User", on_delete=models.SET_NULL, null=True, related_name="created_alerts")\n')
    f.write('    created_at = models.DateTimeField(auto_now_add=True)\n')
    f.write('    resolved_at = models.DateTimeField(null=True, blank=True)\n\n')
    f.write('    class Meta:\n')
    f.write('        db_table = "alerts"\n')
    f.write('        ordering = ["-created_at"]\n\n')
    f.write('    def __str__(self):\n')
    f.write('        return f"{self.alert_type} - {self.title}"\n')
print('Done')
