with open('apps/accounts/tests.py', 'w') as f:
    f.write('from django.test import TestCase\n')
    f.write('from rest_framework.test import APIClient\n')
    f.write('from rest_framework import status\n')
    f.write('from apps.accounts.models import User\n\n')
    f.write('class AuthTests(TestCase):\n')
    f.write('    def setUp(self):\n')
    f.write('        self.client = APIClient()\n')
    f.write('        self.register_url = "/api/auth/register/"\n')
    f.write('        self.login_url = "/api/auth/login/"\n')
    f.write('        self.profile_url = "/api/auth/profile/"\n')
    f.write('        self.user_data = {"email": "testuser@example.com", "password": "testpass123", "role": "manufacturer", "company_name": "Test Co"}\n\n')
    f.write('    def test_register_user(self):\n')
    f.write('        response = self.client.post(self.register_url, self.user_data)\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_201_CREATED)\n')
    f.write('        self.assertIn("access", response.data)\n')
    f.write('        self.assertIn("refresh", response.data)\n\n')
    f.write('    def test_login_user(self):\n')
    f.write('        User.objects.create_user(**self.user_data)\n')
    f.write('        response = self.client.post(self.login_url, {"email": "testuser@example.com", "password": "testpass123"})\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_200_OK)\n')
    f.write('        self.assertIn("access", response.data)\n\n')
    f.write('    def test_login_wrong_password(self):\n')
    f.write('        User.objects.create_user(**self.user_data)\n')
    f.write('        response = self.client.post(self.login_url, {"email": "testuser@example.com", "password": "wrongpass"})\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)\n\n')
    f.write('    def test_profile_requires_auth(self):\n')
    f.write('        response = self.client.get(self.profile_url)\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)\n\n')
    f.write('    def test_profile_authenticated(self):\n')
    f.write('        User.objects.create_user(**self.user_data)\n')
    f.write('        login = self.client.post(self.login_url, {"email": "testuser@example.com", "password": "testpass123"})\n')
    f.write('        self.client.credentials(HTTP_AUTHORIZATION="Bearer " + login.data["access"])\n')
    f.write('        response = self.client.get(self.profile_url)\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_200_OK)\n')
    f.write('        self.assertEqual(response.data["email"], "testuser@example.com")\n')
print('Done')
