with open('apps/drugs/views.py', 'w') as f:
    f.write('from rest_framework import generics, permissions, status\n')
    f.write('from rest_framework.response import Response\n')
    f.write('from rest_framework.views import APIView\n')
    f.write('from .models import Drug, BatchNumber\n')
    f.write('from .serializers import DrugSerializer, BatchNumberSerializer\n')
    f.write('from apps.common.permissions import IsManufacturer\n')
    f.write('from apps.common.qr_utils import generate_batch_qr\n\n')
    f.write('class DrugListCreateView(generics.ListCreateAPIView):\n')
    f.write('    serializer_class = DrugSerializer\n')
    f.write('    def get_permissions(self):\n')
    f.write('        if self.request.method == "POST":\n')
    f.write('            return [permissions.IsAuthenticated(), IsManufacturer()]\n')
    f.write('        return [permissions.IsAuthenticated()]\n')
    f.write('    def get_queryset(self):\n')
    f.write('        user = self.request.user\n')
    f.write('        if user.role == "manufacturer":\n')
    f.write('            return Drug.objects.filter(manufacturer=user)\n')
    f.write('        return Drug.objects.all()\n\n')
    f.write('class DrugDetailView(generics.RetrieveUpdateDestroyAPIView):\n')
    f.write('    serializer_class = DrugSerializer\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get_queryset(self):\n')
    f.write('        user = self.request.user\n')
    f.write('        if user.role == "manufacturer":\n')
    f.write('            return Drug.objects.filter(manufacturer=user)\n')
    f.write('        return Drug.objects.all()\n\n')
    f.write('class BatchListCreateView(generics.ListCreateAPIView):\n')
    f.write('    serializer_class = BatchNumberSerializer\n')
    f.write('    permission_classes = [permissions.IsAuthenticated, IsManufacturer]\n')
    f.write('    def get_queryset(self):\n')
    f.write('        return BatchNumber.objects.filter(drug__manufacturer=self.request.user)\n')
    f.write('    def perform_create(self, serializer):\n')
    f.write('        drug_id = self.kwargs["drug_id"]\n')
    f.write('        drug = Drug.objects.get(id=drug_id, manufacturer=self.request.user)\n')
    f.write('        batch = serializer.save(drug=drug)\n')
    f.write('        qr_data = generate_batch_qr(batch_number=batch.batch_number, drug_id=drug.id, manufacturer_id=self.request.user.id)\n')
    f.write('        batch.qr_code_data = qr_data["qr_data"]\n')
    f.write('        batch.save()\n\n')
    f.write('class BatchQRCodeView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated, IsManufacturer]\n')
    f.write('    def get(self, request, batch_id):\n')
    f.write('        try:\n')
    f.write('            batch = BatchNumber.objects.get(id=batch_id, drug__manufacturer=request.user)\n')
    f.write('            qr_result = generate_batch_qr(batch_number=batch.batch_number, drug_id=batch.drug.id, manufacturer_id=request.user.id)\n')
    f.write('            return Response({"batch_id": str(batch.id), "batch_number": batch.batch_number, "qr_data": qr_result["qr_data"], "qr_image_base64": qr_result["qr_image_base64"]})\n')
    f.write('        except BatchNumber.DoesNotExist:\n')
    f.write('            return Response({"detail": "Batch not found."}, status=status.HTTP_404_NOT_FOUND)\n\n')
    f.write('class DrugVerifyView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get(self, request, nafdac_number):\n')
    f.write('        try:\n')
    f.write('            drug = Drug.objects.get(nafdac_number=nafdac_number)\n')
    f.write('            return Response(DrugSerializer(drug).data)\n')
    f.write('        except Drug.DoesNotExist:\n')
    f.write('            return Response({"detail": "Drug not found."}, status=status.HTTP_404_NOT_FOUND)\n')
print('Done')
