with open('config/settings.py', 'w') as f:
    f.write('import os\n')
    f.write('from pathlib import Path\n')
    f.write('from datetime import timedelta\n\n')
    f.write('BASE_DIR = Path(__file__).resolve().parent.parent\n\n')
    f.write('SECRET_KEY = "django-insecure-dev-key-only"\n')
    f.write('DEBUG = True\n')
    f.write('ALLOWED_HOSTS = ["localhost", "127.0.0.1"]\n\n')
    f.write('INSTALLED_APPS = [\n')
    f.write('    "django.contrib.admin",\n')
    f.write('    "django.contrib.auth",\n')
    f.write('    "django.contrib.contenttypes",\n')
    f.write('    "django.contrib.sessions",\n')
    f.write('    "django.contrib.messages",\n')
    f.write('    "django.contrib.staticfiles",\n')
    f.write('    "rest_framework",\n')
    f.write('    "corsheaders",\n')
    f.write('    "apps.accounts",\n')
    f.write('    "apps.drugs",\n')
    f.write('    "apps.verification",\n')
    f.write('    "apps.supply_chain",\n')
    f.write('    "apps.alerts",\n')
    f.write('    "apps.analytics",\n')
    f.write('    "apps.common",\n')
    f.write(']\n\n')
    f.write('MIDDLEWARE = [\n')
    f.write('    "django.middleware.security.SecurityMiddleware",\n')
    f.write('    "corsheaders.middleware.CorsMiddleware",\n')
    f.write('    "django.contrib.sessions.middleware.SessionMiddleware",\n')
    f.write('    "django.middleware.common.CommonMiddleware",\n')
    f.write('    "django.middleware.csrf.CsrfViewMiddleware",\n')
    f.write('    "django.contrib.auth.middleware.AuthenticationMiddleware",\n')
    f.write('    "django.contrib.messages.middleware.MessageMiddleware",\n')
    f.write('    "django.middleware.clickjacking.XFrameOptionsMiddleware",\n')
    f.write(']\n\n')
    f.write('ROOT_URLCONF = "config.urls"\n\n')
    f.write('TEMPLATES = [{\n')
    f.write('    "BACKEND": "django.template.backends.django.DjangoTemplates",\n')
    f.write('    "DIRS": [],\n')
    f.write('    "APP_DIRS": True,\n')
    f.write('    "OPTIONS": {"context_processors": [\n')
    f.write('        "django.template.context_processors.debug",\n')
    f.write('        "django.template.context_processors.request",\n')
    f.write('        "django.contrib.auth.context_processors.auth",\n')
    f.write('        "django.contrib.messages.context_processors.messages",\n')
    f.write('    ]},\n')
    f.write('}]\n\n')
    f.write('WSGI_APPLICATION = "config.wsgi.application"\n\n')
    f.write('DATABASES = {\n')
    f.write('    "default": {\n')
    f.write('        "ENGINE": "django.db.backends.sqlite3",\n')
    f.write('        "NAME": BASE_DIR / "db.sqlite3",\n')
    f.write('    }\n')
    f.write('}\n\n')
    f.write('AUTH_PASSWORD_VALIDATORS = [\n')
    f.write('    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},\n')
    f.write('    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},\n')
    f.write('    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},\n')
    f.write('    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},\n')
    f.write(']\n\n')
    f.write('AUTH_USER_MODEL = "accounts.User"\n\n')
    f.write('LANGUAGE_CODE = "en-us"\n')
    f.write('TIME_ZONE = "UTC"\n')
    f.write('USE_I18N = True\n')
    f.write('USE_TZ = True\n\n')
    f.write('STATIC_URL = "static/"\n')
    f.write('STATIC_ROOT = BASE_DIR / "staticfiles"\n')
    f.write('MEDIA_URL = "/media/"\n')
    f.write('MEDIA_ROOT = BASE_DIR / "media"\n\n')
    f.write('DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"\n\n')
    f.write('CORS_ALLOW_ALL_ORIGINS = True\n\n')
    f.write('REST_FRAMEWORK = {\n')
    f.write('    "DEFAULT_AUTHENTICATION_CLASSES": (\n')
    f.write('        "rest_framework_simplejwt.authentication.JWTAuthentication",\n')
    f.write('    ),\n')
    f.write('    "DEFAULT_PERMISSION_CLASSES": (\n')
    f.write('        "rest_framework.permissions.IsAuthenticated",\n')
    f.write('    ),\n')
    f.write('}\n\n')
    f.write('SIMPLE_JWT = {\n')
    f.write('    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),\n')
    f.write('    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),\n')
    f.write('}\n')
print('Done')
