with open('apps/accounts/managers.py', 'w') as f:
    f.write('from django.contrib.auth.base_user import BaseUserManager\n')
    f.write('from django.utils.translation import gettext_lazy as _\n\n')
    f.write('class UserManager(BaseUserManager):\n')
    f.write('    def create_user(self, email, password=None, **extra_fields):\n')
    f.write('        if not email:\n')
    f.write('            raise ValueError(_("The Email must be set"))\n')
    f.write('        email = self.normalize_email(email)\n')
    f.write('        user = self.model(email=email, **extra_fields)\n')
    f.write('        user.set_password(password)\n')
    f.write('        user.save(using=self._db)\n')
    f.write('        return user\n\n')
    f.write('    def create_superuser(self, email, password=None, **extra_fields):\n')
    f.write('        extra_fields.setdefault("is_staff", True)\n')
    f.write('        extra_fields.setdefault("is_superuser", True)\n')
    f.write('        extra_fields.setdefault("is_verified", True)\n')
    f.write('        if extra_fields.get("is_staff") is not True:\n')
    f.write('            raise ValueError(_("Superuser must have is_staff=True."))\n')
    f.write('        if extra_fields.get("is_superuser") is not True:\n')
    f.write('            raise ValueError(_("Superuser must have is_superuser=True."))\n')
    f.write('        return self.create_user(email, password, **extra_fields)\n')
print('Done')
