with open('apps/drugs/models.py', 'w') as f:
    f.write('from django.db import models\n')
    f.write('from django.utils.translation import gettext_lazy as _\n')
    f.write('import uuid\n\n')
    f.write('class Drug(models.Model):\n')
    f.write('    class Status(models.TextChoices):\n')
    f.write('        ACTIVE = "active", _("Active")\n')
    f.write('        RECALLED = "recalled", _("Recalled")\n')
    f.write('        EXPIRED = "expired", _("Expired")\n')
    f.write('        SUSPENDED = "suspended", _("Suspended")\n\n')
    f.write('    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)\n')
    f.write('    name = models.CharField(max_length=255)\n')
    f.write('    generic_name = models.CharField(max_length=255, blank=True)\n')
    f.write('    manufacturer = models.ForeignKey("accounts.User", on_delete=models.CASCADE, related_name="drugs", limit_choices_to={"role": "manufacturer"})\n')
    f.write('    nafdac_number = models.CharField(max_length=100, unique=True)\n')
    f.write('    description = models.TextField(blank=True)\n')
    f.write('    dosage_form = models.CharField(max_length=100)\n')
    f.write('    strength = models.CharField(max_length=100)\n')
    f.write('    status = models.CharField(max_length=20, choices=Status.choices, default=Status.ACTIVE)\n')
    f.write('    created_at = models.DateTimeField(auto_now_add=True)\n')
    f.write('    updated_at = models.DateTimeField(auto_now=True)\n\n')
    f.write('    class Meta:\n')
    f.write('        db_table = "drugs"\n')
    f.write('        ordering = ["-created_at"]\n\n')
    f.write('    def __str__(self):\n')
    f.write('        return f"{self.name} ({self.nafdac_number})"\n\n')
    f.write('class BatchNumber(models.Model):\n')
    f.write('    class Status(models.TextChoices):\n')
    f.write('        ACTIVE = "active", _("Active")\n')
    f.write('        RECALLED = "recalled", _("Recalled")\n')
    f.write('        EXPIRED = "expired", _("Expired")\n\n')
    f.write('    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)\n')
    f.write('    drug = models.ForeignKey(Drug, on_delete=models.CASCADE, related_name="batches")\n')
    f.write('    batch_number = models.CharField(max_length=100, unique=True)\n')
    f.write('    manufacture_date = models.DateField()\n')
    f.write('    expiry_date = models.DateField()\n')
    f.write('    quantity = models.PositiveIntegerField()\n')
    f.write('    status = models.CharField(max_length=20, choices=Status.choices, default=Status.ACTIVE)\n')
    f.write('    qr_code_data = models.JSONField(null=True, blank=True)\n')
    f.write('    created_at = models.DateTimeField(auto_now_add=True)\n\n')
    f.write('    class Meta:\n')
    f.write('        db_table = "batch_numbers"\n')
    f.write('        ordering = ["-created_at"]\n\n')
    f.write('    def __str__(self):\n')
    f.write('        return f"{self.drug.name} - Batch {self.batch_number}"\n\n')
    f.write('    @property\n')
    f.write('    def is_expired(self):\n')
    f.write('        from django.utils import timezone\n')
    f.write('        return self.expiry_date < timezone.now().date()\n')
print('Done')
