with open('apps/drugs/urls.py', 'w') as f:
    f.write('from django.urls import path\n')
    f.write('from .views import DrugListCreateView, DrugDetailView, BatchListCreateView, DrugVerifyView, BatchQRCodeView, ApproveDrugView, RejectDrugView, PendingDrugsView\n\n')
    f.write('urlpatterns = [\n')
    f.write('    path("", DrugListCreateView.as_view(), name="drug-list"),\n')
    f.write('    path("pending/", PendingDrugsView.as_view(), name="pending-drugs"),\n')
    f.write('    path("<uuid:pk>/", DrugDetailView.as_view(), name="drug-detail"),\n')
    f.write('    path("<uuid:pk>/approve/", ApproveDrugView.as_view(), name="drug-approve"),\n')
    f.write('    path("<uuid:pk>/reject/", RejectDrugView.as_view(), name="drug-reject"),\n')
    f.write('    path("<uuid:drug_id>/batches/", BatchListCreateView.as_view(), name="batch-list"),\n')
    f.write('    path("batches/<uuid:batch_id>/qr/", BatchQRCodeView.as_view(), name="batch-qr"),\n')
    f.write('    path("verify/<str:nafdac_number>/", DrugVerifyView.as_view(), name="drug-verify"),\n')
    f.write(']\n')
print('Done')
