with open('update_cors.py', 'w', encoding='utf-8') as f:
    f.write('with open("config/settings.py", "r") as f:\n')
    f.write('    content = f.read()\n')
    f.write('content = content.replace(\n')
    f.write('    "\'rest_framework\',",\n')
    f.write('    "\'rest_framework\',\n    \'corsheaders\',"\n')
    f.write(')\n')
    f.write('content = content.replace(\n')
    f.write('    "\'django.middleware.security.SecurityMiddleware\',",\n')
    f.write('    "\'django.middleware.security.SecurityMiddleware\',\n    \'corsheaders.middleware.CorsMiddleware\',"\n')
    f.write(')\n')
    f.write('content += "\nCORS_ALLOWED_ORIGINS = [\n    \'http://localhost:5173\',\n]\n"\n')
    f.write('with open("config/settings.py", "w") as f:\n')
    f.write('    f.write(content)\n')
    f.write('print("Done")\n')
print("Done")
