with open('apps/alerts/views.py', 'w') as f:
    f.write('from rest_framework import generics, permissions\n')
    f.write('from rest_framework.views import APIView\n')
    f.write('from rest_framework.response import Response\n')
    f.write('from django.utils import timezone\n')
    f.write('from .models import Alert\n')
    f.write('from .serializers import AlertSerializer\n\n')
    f.write('class AlertListCreateView(generics.ListCreateAPIView):\n')
    f.write('    serializer_class = AlertSerializer\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get_queryset(self):\n')
    f.write('        queryset = Alert.objects.all()\n')
    f.write('        alert_type = self.request.query_params.get("type")\n')
    f.write('        severity = self.request.query_params.get("severity")\n')
    f.write('        if alert_type:\n')
    f.write('            queryset = queryset.filter(alert_type=alert_type)\n')
    f.write('        if severity:\n')
    f.write('            queryset = queryset.filter(severity=severity)\n')
    f.write('        return queryset\n\n')
    f.write('class AlertDetailView(generics.RetrieveUpdateDestroyAPIView):\n')
    f.write('    serializer_class = AlertSerializer\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    queryset = Alert.objects.all()\n\n')
    f.write('class ResolveAlertView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def post(self, request, pk):\n')
    f.write('        try:\n')
    f.write('            alert = Alert.objects.get(pk=pk)\n')
    f.write('            alert.is_resolved = True\n')
    f.write('            alert.resolved_at = timezone.now()\n')
    f.write('            alert.save()\n')
    f.write('            return Response({"detail": "Alert resolved.", "id": str(alert.id)})\n')
    f.write('        except Alert.DoesNotExist:\n')
    f.write('            return Response({"detail": "Alert not found."}, status=404)\n')
print('Done')
