with open('apps/drugs/serializers.py', 'w') as f:
    f.write('from rest_framework import serializers\n')
    f.write('from .models import Drug, BatchNumber\n\n')
    f.write('class BatchNumberSerializer(serializers.ModelSerializer):\n')
    f.write('    is_expired = serializers.ReadOnlyField()\n')
    f.write('    class Meta:\n')
    f.write('        model = BatchNumber\n')
    f.write('        fields = ["id", "batch_number", "manufacture_date", "expiry_date", "quantity", "status", "is_expired", "created_at"]\n')
    f.write('        read_only_fields = ["id", "created_at"]\n\n')
    f.write('class DrugSerializer(serializers.ModelSerializer):\n')
    f.write('    batches = BatchNumberSerializer(many=True, read_only=True)\n')
    f.write('    manufacturer_name = serializers.CharField(source="manufacturer.company_name", read_only=True)\n')
    f.write('    class Meta:\n')
    f.write('        model = Drug\n')
    f.write('        fields = ["id", "name", "generic_name", "nafdac_number", "description", "dosage_form", "strength", "status", "manufacturer", "manufacturer_name", "batches", "created_at"]\n')
    f.write('        read_only_fields = ["id", "manufacturer", "created_at"]\n')
    f.write('    def create(self, validated_data):\n')
    f.write('        validated_data["manufacturer"] = self.context["request"].user\n')
    f.write('        return super().create(validated_data)\n')
print('Done')
