with open('apps/supply_chain/serializers.py', 'w') as f:
    f.write('from rest_framework import serializers\n')
    f.write('from .models import SupplyChainEvent\n\n')
    f.write('class SupplyChainEventSerializer(serializers.ModelSerializer):\n')
    f.write('    actor_email = serializers.CharField(source="actor.email", read_only=True)\n')
    f.write('    actor_company = serializers.CharField(source="actor.company_name", read_only=True)\n')
    f.write('    batch_number = serializers.CharField(source="batch.batch_number", read_only=True)\n')
    f.write('    drug_name = serializers.CharField(source="batch.drug.name", read_only=True)\n')
    f.write('    class Meta:\n')
    f.write('        model = SupplyChainEvent\n')
    f.write('        fields = ["id", "batch", "batch_number", "drug_name", "event_type", "actor", "actor_email", "actor_company", "location", "notes", "timestamp"]\n')
    f.write('        read_only_fields = ["id", "actor", "timestamp"]\n')
    f.write('    def create(self, validated_data):\n')
    f.write('        validated_data["actor"] = self.context["request"].user\n')
    f.write('        return super().create(validated_data)\n')
print('Done')
