with open('apps/alerts/serializers.py', 'w') as f:
    f.write('from rest_framework import serializers\n')
    f.write('from .models import Alert\n\n')
    f.write('class AlertSerializer(serializers.ModelSerializer):\n')
    f.write('    created_by_email = serializers.CharField(source="created_by.email", read_only=True)\n')
    f.write('    drug_name = serializers.CharField(source="drug.name", read_only=True)\n')
    f.write('    class Meta:\n')
    f.write('        model = Alert\n')
    f.write('        fields = ["id", "drug", "drug_name", "alert_type", "severity", "title", "message", "is_resolved", "created_by", "created_by_email", "created_at", "resolved_at"]\n')
    f.write('        read_only_fields = ["id", "created_by", "created_at", "resolved_at"]\n')
    f.write('    def create(self, validated_data):\n')
    f.write('        validated_data["created_by"] = self.context["request"].user\n')
    f.write('        return super().create(validated_data)\n')
print('Done')
