with open('apps/drugs/tests.py', 'w') as f:
    f.write('from django.test import TestCase\n')
    f.write('from rest_framework.test import APIClient\n')
    f.write('from rest_framework import status\n')
    f.write('from apps.accounts.models import User\n')
    f.write('from .models import Drug, BatchNumber\n\n')
    f.write('class DrugTests(TestCase):\n')
    f.write('    def setUp(self):\n')
    f.write('        self.client = APIClient()\n')
    f.write('        self.manufacturer = User.objects.create_user(email="mfr@example.com", password="pass1234", role="manufacturer", company_name="Test Pharma")\n')
    f.write('        self.pharmacist = User.objects.create_user(email="pharm@example.com", password="pass1234", role="pharmacist")\n')
    f.write('        self.drug_data = {"name": "Aspirin", "generic_name": "Acetylsalicylic acid", "nafdac_number": "B1-0001", "description": "Pain relief", "dosage_form": "Tablet", "strength": "100mg"}\n\n')
    f.write('    def authenticate(self, email, password):\n')
    f.write('        response = self.client.post("/api/auth/login/", {"email": email, "password": password})\n')
    f.write('        self.client.credentials(HTTP_AUTHORIZATION="Bearer " + response.data["access"])\n\n')
    f.write('    def test_manufacturer_can_create_drug(self):\n')
    f.write('        self.authenticate("mfr@example.com", "pass1234")\n')
    f.write('        response = self.client.post("/api/drugs/", self.drug_data)\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_201_CREATED)\n')
    f.write('        self.assertEqual(response.data["name"], "Aspirin")\n\n')
    f.write('    def test_pharmacist_cannot_create_drug(self):\n')
    f.write('        self.authenticate("pharm@example.com", "pass1234")\n')
    f.write('        response = self.client.post("/api/drugs/", self.drug_data)\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)\n\n')
    f.write('    def test_anyone_can_list_drugs(self):\n')
    f.write('        self.authenticate("pharm@example.com", "pass1234")\n')
    f.write('        response = self.client.get("/api/drugs/")\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_200_OK)\n\n')
    f.write('    def test_verify_drug_by_nafdac(self):\n')
    f.write('        self.authenticate("mfr@example.com", "pass1234")\n')
    f.write('        self.client.post("/api/drugs/", self.drug_data)\n')
    f.write('        response = self.client.get("/api/drugs/verify/B1-0001/")\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_200_OK)\n')
    f.write('        self.assertEqual(response.data["nafdac_number"], "B1-0001")\n')
print('Done')
