with open('apps/analytics/views.py', 'w') as f:
    f.write('from rest_framework.views import APIView\n')
    f.write('from rest_framework.response import Response\n')
    f.write('from rest_framework import permissions\n')
    f.write('from apps.drugs.models import Drug, BatchNumber\n')
    f.write('from apps.verification.models import VerificationLog\n')
    f.write('from apps.alerts.models import Alert\n')
    f.write('from apps.supply_chain.models import SupplyChainEvent\n')
    f.write('from django.db.models import Count\n\n')
    f.write('class DashboardStatsView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get(self, request):\n')
    f.write('        user = request.user\n')
    f.write('        stats = {\n')
    f.write('            "total_drugs": Drug.objects.filter(manufacturer=user).count() if user.role == "manufacturer" else Drug.objects.count(),\n')
    f.write('            "total_batches": BatchNumber.objects.count(),\n')
    f.write('            "total_verifications": VerificationLog.objects.count(),\n')
    f.write('            "authentic_verifications": VerificationLog.objects.filter(result="authentic").count(),\n')
    f.write('            "counterfeit_verifications": VerificationLog.objects.filter(result="counterfeit").count(),\n')
    f.write('            "not_found_verifications": VerificationLog.objects.filter(result="not_found").count(),\n')
    f.write('            "total_alerts": Alert.objects.count(),\n')
    f.write('            "unresolved_alerts": Alert.objects.filter(is_resolved=False).count(),\n')
    f.write('            "total_supply_chain_events": SupplyChainEvent.objects.count(),\n')
    f.write('        }\n')
    f.write('        return Response(stats)\n\n')
    f.write('class VerificationStatsView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get(self, request):\n')
    f.write('        stats = VerificationLog.objects.values("result").annotate(count=Count("result")).order_by("-count")\n')
    f.write('        return Response(list(stats))\n\n')
    f.write('class AlertStatsView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get(self, request):\n')
    f.write('        by_type = Alert.objects.values("alert_type").annotate(count=Count("alert_type"))\n')
    f.write('        by_severity = Alert.objects.values("severity").annotate(count=Count("severity"))\n')
    f.write('        return Response({"by_type": list(by_type), "by_severity": list(by_severity)})\n')
print('Done')
