with open('apps/verification/tests.py', 'w') as f:
    f.write('from django.test import TestCase\n')
    f.write('from rest_framework.test import APIClient\n')
    f.write('from rest_framework import status\n')
    f.write('from apps.accounts.models import User\n')
    f.write('from apps.drugs.models import Drug, BatchNumber\n')
    f.write('from datetime import date\n\n')
    f.write('class VerificationTests(TestCase):\n')
    f.write('    def setUp(self):\n')
    f.write('        self.client = APIClient()\n')
    f.write('        self.manufacturer = User.objects.create_user(email="mfr@example.com", password="pass1234", role="manufacturer", company_name="Test Pharma")\n')
    f.write('        self.pharmacist = User.objects.create_user(email="pharm@example.com", password="pass1234", role="pharmacist")\n')
    f.write('        self.drug = Drug.objects.create(name="Aspirin", nafdac_number="C1-0001", manufacturer=self.manufacturer, dosage_form="Tablet", strength="100mg")\n')
    f.write('        self.batch = BatchNumber.objects.create(drug=self.drug, batch_number="TEST-001", manufacture_date=date(2026,1,1), expiry_date=date(2028,1,1), quantity=500)\n\n')
    f.write('    def authenticate(self, email, password):\n')
    f.write('        response = self.client.post("/api/auth/login/", {"email": email, "password": password})\n')
    f.write('        self.client.credentials(HTTP_AUTHORIZATION="Bearer " + response.data["access"])\n\n')
    f.write('    def test_verify_authentic_batch(self):\n')
    f.write('        self.authenticate("pharm@example.com", "pass1234")\n')
    f.write('        response = self.client.post("/api/verification/verify/", {"scanned_code": "TEST-001", "location": "Lagos"})\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_200_OK)\n')
    f.write('        self.assertEqual(response.data["result"], "authentic")\n\n')
    f.write('    def test_verify_not_found(self):\n')
    f.write('        self.authenticate("pharm@example.com", "pass1234")\n')
    f.write('        response = self.client.post("/api/verification/verify/", {"scanned_code": "FAKE-999", "location": "Lagos"})\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_200_OK)\n')
    f.write('        self.assertEqual(response.data["result"], "not_found")\n\n')
    f.write('    def test_verify_recalled_batch(self):\n')
    f.write('        self.batch.status = "recalled"\n')
    f.write('        self.batch.save()\n')
    f.write('        self.authenticate("pharm@example.com", "pass1234")\n')
    f.write('        response = self.client.post("/api/verification/verify/", {"scanned_code": "TEST-001", "location": "Lagos"})\n')
    f.write('        self.assertEqual(response.data["result"], "recalled")\n\n')
    f.write('    def test_verification_history(self):\n')
    f.write('        self.authenticate("pharm@example.com", "pass1234")\n')
    f.write('        self.client.post("/api/verification/verify/", {"scanned_code": "TEST-001", "location": "Lagos"})\n')
    f.write('        response = self.client.get("/api/verification/history/")\n')
    f.write('        self.assertEqual(response.status_code, status.HTTP_200_OK)\n')
    f.write('        self.assertEqual(len(response.data), 1)\n')
print('Done')
