with open('apps/drugs/views.py', 'w') as f:
    f.write('from rest_framework import generics, permissions, status\n')
    f.write('from rest_framework.response import Response\n')
    f.write('from rest_framework.views import APIView\n')
    f.write('from .models import Drug, BatchNumber\n')
    f.write('from .serializers import DrugSerializer, BatchNumberSerializer\n\n')
    f.write('class IsManufacturer(permissions.BasePermission):\n')
    f.write('    def has_permission(self, request, view):\n')
    f.write('        return request.user.role == "manufacturer"\n\n')
    f.write('class DrugListCreateView(generics.ListCreateAPIView):\n')
    f.write('    serializer_class = DrugSerializer\n')
    f.write('    def get_permissions(self):\n')
    f.write('        if self.request.method == "POST":\n')
    f.write('            return [permissions.IsAuthenticated(), IsManufacturer()]\n')
    f.write('        return [permissions.IsAuthenticated()]\n')
    f.write('    def get_queryset(self):\n')
    f.write('        user = self.request.user\n')
    f.write('        if user.role == "manufacturer":\n')
    f.write('            return Drug.objects.filter(manufacturer=user)\n')
    f.write('        return Drug.objects.all()\n\n')
    f.write('class DrugDetailView(generics.RetrieveUpdateDestroyAPIView):\n')
    f.write('    serializer_class = DrugSerializer\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get_queryset(self):\n')
    f.write('        user = self.request.user\n')
    f.write('        if user.role == "manufacturer":\n')
    f.write('            return Drug.objects.filter(manufacturer=user)\n')
    f.write('        return Drug.objects.all()\n\n')
    f.write('class BatchListCreateView(generics.ListCreateAPIView):\n')
    f.write('    serializer_class = BatchNumberSerializer\n')
    f.write('    permission_classes = [permissions.IsAuthenticated, IsManufacturer]\n')
    f.write('    def get_queryset(self):\n')
    f.write('        return BatchNumber.objects.filter(drug__manufacturer=self.request.user)\n')
    f.write('    def perform_create(self, serializer):\n')
    f.write('        drug_id = self.kwargs["drug_id"]\n')
    f.write('        drug = Drug.objects.get(id=drug_id, manufacturer=self.request.user)\n')
    f.write('        serializer.save(drug=drug)\n\n')
    f.write('class DrugVerifyView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get(self, request, nafdac_number):\n')
    f.write('        try:\n')
    f.write('            drug = Drug.objects.get(nafdac_number=nafdac_number)\n')
    f.write('            return Response(DrugSerializer(drug).data)\n')
    f.write('        except Drug.DoesNotExist:\n')
    f.write('            return Response({"detail": "Drug not found."}, status=status.HTTP_404_NOT_FOUND)\n')
print('Done')
