with open('apps/accounts/views.py', 'w') as f:
    f.write('from rest_framework.views import APIView\n')
    f.write('from rest_framework.response import Response\n')
    f.write('from rest_framework import status, permissions\n')
    f.write('from rest_framework_simplejwt.tokens import RefreshToken\n')
    f.write('from django.contrib.auth import update_session_auth_hash\n')
    f.write('from .serializers import RegisterSerializer, LoginSerializer, UserSerializer\n')
    f.write('from .models import User\n\n')
    f.write('class RegisterView(APIView):\n')
    f.write('    permission_classes = [permissions.AllowAny]\n')
    f.write('    def post(self, request):\n')
    f.write('        serializer = RegisterSerializer(data=request.data)\n')
    f.write('        if serializer.is_valid():\n')
    f.write('            user = serializer.save()\n')
    f.write('            refresh = RefreshToken.for_user(user)\n')
    f.write('            return Response({"user": UserSerializer(user).data, "refresh": str(refresh), "access": str(refresh.access_token)}, status=status.HTTP_201_CREATED)\n')
    f.write('        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)\n\n')
    f.write('class LoginView(APIView):\n')
    f.write('    permission_classes = [permissions.AllowAny]\n')
    f.write('    def post(self, request):\n')
    f.write('        serializer = LoginSerializer(data=request.data)\n')
    f.write('        if serializer.is_valid():\n')
    f.write('            user = serializer.validated_data["user"]\n')
    f.write('            refresh = RefreshToken.for_user(user)\n')
    f.write('            return Response({"user": UserSerializer(user).data, "refresh": str(refresh), "access": str(refresh.access_token)})\n')
    f.write('        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)\n\n')
    f.write('class ProfileView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get(self, request):\n')
    f.write('        return Response(UserSerializer(request.user).data)\n')
    f.write('    def patch(self, request):\n')
    f.write('        serializer = UserSerializer(request.user, data=request.data, partial=True)\n')
    f.write('        if serializer.is_valid():\n')
    f.write('            serializer.save()\n')
    f.write('            return Response(serializer.data)\n')
    f.write('        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)\n\n')
    f.write('class ChangePasswordView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def post(self, request):\n')
    f.write('        user = request.user\n')
    f.write('        old_password = request.data.get("old_password")\n')
    f.write('        new_password = request.data.get("new_password")\n')
    f.write('        if not user.check_password(old_password):\n')
    f.write('            return Response({"detail": "Old password is incorrect."}, status=status.HTTP_400_BAD_REQUEST)\n')
    f.write('        if not new_password or len(new_password) < 8:\n')
    f.write('            return Response({"detail": "New password must be at least 8 characters."}, status=status.HTTP_400_BAD_REQUEST)\n')
    f.write('        user.set_password(new_password)\n')
    f.write('        user.save()\n')
    f.write('        return Response({"detail": "Password changed successfully."})\n\n')
    f.write('class UserListView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get(self, request):\n')
    f.write('        if request.user.role not in ["regulator", "admin"]:\n')
    f.write('            return Response({"detail": "Permission denied."}, status=status.HTTP_403_FORBIDDEN)\n')
    f.write('        role = request.query_params.get("role")\n')
    f.write('        users = User.objects.all()\n')
    f.write('        if role:\n')
    f.write('            users = users.filter(role=role)\n')
    f.write('        return Response(UserSerializer(users, many=True).data)\n')
print('Done')
