with open('apps/verification/views.py', 'w') as f:
    f.write('from rest_framework.views import APIView\n')
    f.write('from rest_framework.response import Response\n')
    f.write('from rest_framework import permissions, status\n')
    f.write('from apps.drugs.models import BatchNumber\n')
    f.write('from .models import VerificationLog\n')
    f.write('from .serializers import VerificationLogSerializer\n')
    f.write('from django.utils import timezone\n\n')
    f.write('class VerifyDrugView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def post(self, request):\n')
    f.write('        scanned_code = request.data.get("scanned_code")\n')
    f.write('        location = request.data.get("location", "")\n')
    f.write('        if not scanned_code:\n')
    f.write('            return Response({"detail": "scanned_code is required."}, status=status.HTTP_400_BAD_REQUEST)\n')
    f.write('        try:\n')
    f.write('            batch = BatchNumber.objects.get(batch_number=scanned_code)\n')
    f.write('            if batch.status == "recalled":\n')
    f.write('                result = "recalled"\n')
    f.write('            elif batch.is_expired:\n')
    f.write('                result = "expired"\n')
    f.write('            else:\n')
    f.write('                result = "authentic"\n')
    f.write('        except BatchNumber.DoesNotExist:\n')
    f.write('            batch = None\n')
    f.write('            result = "not_found"\n')
    f.write('        log = VerificationLog.objects.create(\n')
    f.write('            batch=batch,\n')
    f.write('            verified_by=request.user,\n')
    f.write('            scanned_code=scanned_code,\n')
    f.write('            result=result,\n')
    f.write('            location=location,\n')
    f.write('            ip_address=request.META.get("REMOTE_ADDR")\n')
    f.write('        )\n')
    f.write('        return Response({"result": result, "scanned_code": scanned_code, "batch": str(batch) if batch else None}, status=status.HTTP_200_OK)\n\n')
    f.write('class VerificationHistoryView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get(self, request):\n')
    f.write('        logs = VerificationLog.objects.filter(verified_by=request.user)\n')
    f.write('        serializer = VerificationLogSerializer(logs, many=True)\n')
    f.write('        return Response(serializer.data)\n')
print('Done')
