with open('apps/supply_chain/views.py', 'w') as f:
    f.write('from rest_framework import generics, permissions\n')
    f.write('from rest_framework.response import Response\n')
    f.write('from rest_framework.views import APIView\n')
    f.write('from .models import SupplyChainEvent\n')
    f.write('from .serializers import SupplyChainEventSerializer\n\n')
    f.write('class SupplyChainEventListCreateView(generics.ListCreateAPIView):\n')
    f.write('    serializer_class = SupplyChainEventSerializer\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get_queryset(self):\n')
    f.write('        user = self.request.user\n')
    f.write('        if user.role in ["regulator", "admin"]:\n')
    f.write('            return SupplyChainEvent.objects.all()\n')
    f.write('        return SupplyChainEvent.objects.filter(actor=user)\n\n')
    f.write('class BatchSupplyChainView(APIView):\n')
    f.write('    permission_classes = [permissions.IsAuthenticated]\n')
    f.write('    def get(self, request, batch_id):\n')
    f.write('        events = SupplyChainEvent.objects.filter(batch__id=batch_id).order_by("timestamp")\n')
    f.write('        serializer = SupplyChainEventSerializer(events, many=True)\n')
    f.write('        return Response(serializer.data)\n')
print('Done')
