# Generated by Django 5.1.15 on 2026-04-02 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('nafdac_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('dosage_form', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('recalled', 'Recalled'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(limit_choices_to={'role': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drugs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('recalled', 'Recalled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('qr_code_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='drugs.drug')),
            ],
            options={
                'db_table': 'batch_numbers',
                'ordering': ['-created_at'],
            },
        ),
    ]
