# Generated by Django 5.1.15 on 2026-04-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('recalled', 'Recalled'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
