# Generated by Django 5.1.15 on 2026-04-08 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_alter_drug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drugs/images/'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='nafdac_number',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='NAFDAC number must follow format: A4-1234 (Letter + Number + dash + 4 digits)', regex='^[A-Z][0-9]-[0-9]{4}$')]),
        ),
    ]
