# Generated by Django 5.1.15 on 2026-04-02 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('manufactured', 'Manufactured'), ('shipped', 'Shipped'), ('received', 'Received'), ('distributed', 'Distributed'), ('sold', 'Sold'), ('returned', 'Returned')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_chain_events', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_chain_events', to='drugs.batchnumber')),
            ],
            options={
                'db_table': 'supply_chain_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
